# Generated by Django 3.2.9 on 2021-11-24 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question1', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3)])),
                ('question2', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3)])),
                ('question3', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3)])),
                ('question4', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3)])),
                ('question5', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3)])),
                ('question6', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3)])),
                ('question7', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3)])),
                ('sexo', models.CharField(max_length=10)),
                ('edad', models.IntegerField()),
                ('option1', models.CharField(blank=True, max_length=100, null=True)),
                ('option2', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'verbose_name': 'Test',
                'verbose_name_plural': 'Tests',
            },
        ),
    ]
